// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"bomond-tenis/internal/api/models"
)

// PostV1BomondVnAuthLogoutOKCode is the HTTP code returned for type PostV1BomondVnAuthLogoutOK
const PostV1BomondVnAuthLogoutOKCode int = 200

/*
PostV1BomondVnAuthLogoutOK User successfully logged out

swagger:response postV1BomondVnAuthLogoutOK
*/
type PostV1BomondVnAuthLogoutOK struct {

	/*
	  In: Body
	*/
	Payload *models.SuccessResponse `json:"body,omitempty"`
}

// NewPostV1BomondVnAuthLogoutOK creates PostV1BomondVnAuthLogoutOK with default headers values
func NewPostV1BomondVnAuthLogoutOK() *PostV1BomondVnAuthLogoutOK {

	return &PostV1BomondVnAuthLogoutOK{}
}

// WithPayload adds the payload to the post v1 bomond vn auth logout o k response
func (o *PostV1BomondVnAuthLogoutOK) WithPayload(payload *models.SuccessResponse) *PostV1BomondVnAuthLogoutOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post v1 bomond vn auth logout o k response
func (o *PostV1BomondVnAuthLogoutOK) SetPayload(payload *models.SuccessResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostV1BomondVnAuthLogoutOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostV1BomondVnAuthLogoutBadRequestCode is the HTTP code returned for type PostV1BomondVnAuthLogoutBadRequest
const PostV1BomondVnAuthLogoutBadRequestCode int = 400

/*
PostV1BomondVnAuthLogoutBadRequest Bad request

swagger:response postV1BomondVnAuthLogoutBadRequest
*/
type PostV1BomondVnAuthLogoutBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResult `json:"body,omitempty"`
}

// NewPostV1BomondVnAuthLogoutBadRequest creates PostV1BomondVnAuthLogoutBadRequest with default headers values
func NewPostV1BomondVnAuthLogoutBadRequest() *PostV1BomondVnAuthLogoutBadRequest {

	return &PostV1BomondVnAuthLogoutBadRequest{}
}

// WithPayload adds the payload to the post v1 bomond vn auth logout bad request response
func (o *PostV1BomondVnAuthLogoutBadRequest) WithPayload(payload *models.ErrorResult) *PostV1BomondVnAuthLogoutBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post v1 bomond vn auth logout bad request response
func (o *PostV1BomondVnAuthLogoutBadRequest) SetPayload(payload *models.ErrorResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostV1BomondVnAuthLogoutBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
