// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"bomond-tenis/internal/api/models"
)

// PostV1BomondVnAuthSignInOKCode is the HTTP code returned for type PostV1BomondVnAuthSignInOK
const PostV1BomondVnAuthSignInOKCode int = 200

/*
PostV1BomondVnAuthSignInOK User successfully signed in

swagger:response postV1BomondVnAuthSignInOK
*/
type PostV1BomondVnAuthSignInOK struct {

	/*
	  In: Body
	*/
	Payload *models.SuccessResponse `json:"body,omitempty"`
}

// NewPostV1BomondVnAuthSignInOK creates PostV1BomondVnAuthSignInOK with default headers values
func NewPostV1BomondVnAuthSignInOK() *PostV1BomondVnAuthSignInOK {

	return &PostV1BomondVnAuthSignInOK{}
}

// WithPayload adds the payload to the post v1 bomond vn auth sign in o k response
func (o *PostV1BomondVnAuthSignInOK) WithPayload(payload *models.SuccessResponse) *PostV1BomondVnAuthSignInOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post v1 bomond vn auth sign in o k response
func (o *PostV1BomondVnAuthSignInOK) SetPayload(payload *models.SuccessResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostV1BomondVnAuthSignInOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostV1BomondVnAuthSignInBadRequestCode is the HTTP code returned for type PostV1BomondVnAuthSignInBadRequest
const PostV1BomondVnAuthSignInBadRequestCode int = 400

/*
PostV1BomondVnAuthSignInBadRequest Bad request

swagger:response postV1BomondVnAuthSignInBadRequest
*/
type PostV1BomondVnAuthSignInBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResult `json:"body,omitempty"`
}

// NewPostV1BomondVnAuthSignInBadRequest creates PostV1BomondVnAuthSignInBadRequest with default headers values
func NewPostV1BomondVnAuthSignInBadRequest() *PostV1BomondVnAuthSignInBadRequest {

	return &PostV1BomondVnAuthSignInBadRequest{}
}

// WithPayload adds the payload to the post v1 bomond vn auth sign in bad request response
func (o *PostV1BomondVnAuthSignInBadRequest) WithPayload(payload *models.ErrorResult) *PostV1BomondVnAuthSignInBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post v1 bomond vn auth sign in bad request response
func (o *PostV1BomondVnAuthSignInBadRequest) SetPayload(payload *models.ErrorResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostV1BomondVnAuthSignInBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
