// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostV1BomondVnAuthLogoutHandlerFunc turns a function with the right signature into a post v1 bomond vn auth logout handler
type PostV1BomondVnAuthLogoutHandlerFunc func(PostV1BomondVnAuthLogoutParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostV1BomondVnAuthLogoutHandlerFunc) Handle(params PostV1BomondVnAuthLogoutParams) middleware.Responder {
	return fn(params)
}

// PostV1BomondVnAuthLogoutHandler interface for that can handle valid post v1 bomond vn auth logout params
type PostV1BomondVnAuthLogoutHandler interface {
	Handle(PostV1BomondVnAuthLogoutParams) middleware.Responder
}

// NewPostV1BomondVnAuthLogout creates a new http.Handler for the post v1 bomond vn auth logout operation
func NewPostV1BomondVnAuthLogout(ctx *middleware.Context, handler PostV1BomondVnAuthLogoutHandler) *PostV1BomondVnAuthLogout {
	return &PostV1BomondVnAuthLogout{Context: ctx, Handler: handler}
}

/*
	PostV1BomondVnAuthLogout swagger:route POST /v1/bomond.vn/auth/logout Authentication postV1BomondVnAuthLogout

PostV1BomondVnAuthLogout post v1 bomond vn auth logout API
*/
type PostV1BomondVnAuthLogout struct {
	Context *middleware.Context
	Handler PostV1BomondVnAuthLogoutHandler
}

func (o *PostV1BomondVnAuthLogout) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostV1BomondVnAuthLogoutParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
