// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewPostV1BomondVnAuthLogoutParams creates a new PostV1BomondVnAuthLogoutParams object
//
// There are no default values defined in the spec.
func NewPostV1BomondVnAuthLogoutParams() PostV1BomondVnAuthLogoutParams {

	return PostV1BomondVnAuthLogoutParams{}
}

// PostV1BomondVnAuthLogoutParams contains all the bound params for the post v1 bomond vn auth logout operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostV1BomondVnAuthLogout
type PostV1BomondVnAuthLogoutParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*JWT token for authorization
	  Required: true
	  In: header
	*/
	Authorization string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostV1BomondVnAuthLogoutParams() beforehand.
func (o *PostV1BomondVnAuthLogoutParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := o.bindAuthorization(r.Header[http.CanonicalHeaderKey("Authorization")], true, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAuthorization binds and validates parameter Authorization from header.
func (o *PostV1BomondVnAuthLogoutParams) bindAuthorization(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("Authorization", "header", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("Authorization", "header", raw); err != nil {
		return err
	}
	o.Authorization = raw

	return nil
}
