// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostV1BomondVnAuthSignInHandlerFunc turns a function with the right signature into a post v1 bomond vn auth sign in handler
type PostV1BomondVnAuthSignInHandlerFunc func(PostV1BomondVnAuthSignInParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostV1BomondVnAuthSignInHandlerFunc) Handle(params PostV1BomondVnAuthSignInParams) middleware.Responder {
	return fn(params)
}

// PostV1BomondVnAuthSignInHandler interface for that can handle valid post v1 bomond vn auth sign in params
type PostV1BomondVnAuthSignInHandler interface {
	Handle(PostV1BomondVnAuthSignInParams) middleware.Responder
}

// NewPostV1BomondVnAuthSignIn creates a new http.Handler for the post v1 bomond vn auth sign in operation
func NewPostV1BomondVnAuthSignIn(ctx *middleware.Context, handler PostV1BomondVnAuthSignInHandler) *PostV1BomondVnAuthSignIn {
	return &PostV1BomondVnAuthSignIn{Context: ctx, Handler: handler}
}

/*
	PostV1BomondVnAuthSignIn swagger:route POST /v1/bomond.vn/auth/sign-in Authentication postV1BomondVnAuthSignIn

PostV1BomondVnAuthSignIn post v1 bomond vn auth sign in API
*/
type PostV1BomondVnAuthSignIn struct {
	Context *middleware.Context
	Handler PostV1BomondVnAuthSignInHandler
}

func (o *PostV1BomondVnAuthSignIn) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostV1BomondVnAuthSignInParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostV1BomondVnAuthSignInBody post v1 bomond vn auth sign in body
//
// swagger:model PostV1BomondVnAuthSignInBody
type PostV1BomondVnAuthSignInBody struct {

	// email
	Email string `json:"email,omitempty"`

	// password
	Password string `json:"password,omitempty"`
}

// Validate validates this post v1 bomond vn auth sign in body
func (o *PostV1BomondVnAuthSignInBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post v1 bomond vn auth sign in body based on context it is used
func (o *PostV1BomondVnAuthSignInBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostV1BomondVnAuthSignInBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostV1BomondVnAuthSignInBody) UnmarshalBinary(b []byte) error {
	var res PostV1BomondVnAuthSignInBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
