// Code generated by go-swagger; DO NOT EDIT.

package courts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"bomond-tenis/internal/api/models"
)

// DeleteV1BomondVnCourtIDBookBookIDOKCode is the HTTP code returned for type DeleteV1BomondVnCourtIDBookBookIDOK
const DeleteV1BomondVnCourtIDBookBookIDOKCode int = 200

/*
DeleteV1BomondVnCourtIDBookBookIDOK Booking successfully deleted

swagger:response deleteV1BomondVnCourtIdBookBookIdOK
*/
type DeleteV1BomondVnCourtIDBookBookIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.SuccessResponse `json:"body,omitempty"`
}

// NewDeleteV1BomondVnCourtIDBookBookIDOK creates DeleteV1BomondVnCourtIDBookBookIDOK with default headers values
func NewDeleteV1BomondVnCourtIDBookBookIDOK() *DeleteV1BomondVnCourtIDBookBookIDOK {

	return &DeleteV1BomondVnCourtIDBookBookIDOK{}
}

// WithPayload adds the payload to the delete v1 bomond vn court Id book book Id o k response
func (o *DeleteV1BomondVnCourtIDBookBookIDOK) WithPayload(payload *models.SuccessResponse) *DeleteV1BomondVnCourtIDBookBookIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete v1 bomond vn court Id book book Id o k response
func (o *DeleteV1BomondVnCourtIDBookBookIDOK) SetPayload(payload *models.SuccessResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteV1BomondVnCourtIDBookBookIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteV1BomondVnCourtIDBookBookIDBadRequestCode is the HTTP code returned for type DeleteV1BomondVnCourtIDBookBookIDBadRequest
const DeleteV1BomondVnCourtIDBookBookIDBadRequestCode int = 400

/*
DeleteV1BomondVnCourtIDBookBookIDBadRequest Bad request

swagger:response deleteV1BomondVnCourtIdBookBookIdBadRequest
*/
type DeleteV1BomondVnCourtIDBookBookIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResult `json:"body,omitempty"`
}

// NewDeleteV1BomondVnCourtIDBookBookIDBadRequest creates DeleteV1BomondVnCourtIDBookBookIDBadRequest with default headers values
func NewDeleteV1BomondVnCourtIDBookBookIDBadRequest() *DeleteV1BomondVnCourtIDBookBookIDBadRequest {

	return &DeleteV1BomondVnCourtIDBookBookIDBadRequest{}
}

// WithPayload adds the payload to the delete v1 bomond vn court Id book book Id bad request response
func (o *DeleteV1BomondVnCourtIDBookBookIDBadRequest) WithPayload(payload *models.ErrorResult) *DeleteV1BomondVnCourtIDBookBookIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete v1 bomond vn court Id book book Id bad request response
func (o *DeleteV1BomondVnCourtIDBookBookIDBadRequest) SetPayload(payload *models.ErrorResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteV1BomondVnCourtIDBookBookIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
