// Code generated by go-swagger; DO NOT EDIT.

package courts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"bomond-tenis/internal/api/models"
)

// DeleteV1BomondCourtIDBookBookIDOKCode is the HTTP code returned for type DeleteV1BomondCourtIDBookBookIDOK
const DeleteV1BomondCourtIDBookBookIDOKCode int = 200

/*
DeleteV1BomondCourtIDBookBookIDOK Booking successfully deleted

swagger:response deleteV1BomondCourtIdBookBookIdOK
*/
type DeleteV1BomondCourtIDBookBookIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.SuccessResponse `json:"body,omitempty"`
}

// NewDeleteV1BomondCourtIDBookBookIDOK creates DeleteV1BomondCourtIDBookBookIDOK with default headers values
func NewDeleteV1BomondCourtIDBookBookIDOK() *DeleteV1BomondCourtIDBookBookIDOK {

	return &DeleteV1BomondCourtIDBookBookIDOK{}
}

// WithPayload adds the payload to the delete v1 bomond court Id book book Id o k response
func (o *DeleteV1BomondCourtIDBookBookIDOK) WithPayload(payload *models.SuccessResponse) *DeleteV1BomondCourtIDBookBookIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete v1 bomond court Id book book Id o k response
func (o *DeleteV1BomondCourtIDBookBookIDOK) SetPayload(payload *models.SuccessResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteV1BomondCourtIDBookBookIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteV1BomondCourtIDBookBookIDBadRequestCode is the HTTP code returned for type DeleteV1BomondCourtIDBookBookIDBadRequest
const DeleteV1BomondCourtIDBookBookIDBadRequestCode int = 400

/*
DeleteV1BomondCourtIDBookBookIDBadRequest Bad request

swagger:response deleteV1BomondCourtIdBookBookIdBadRequest
*/
type DeleteV1BomondCourtIDBookBookIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResult `json:"body,omitempty"`
}

// NewDeleteV1BomondCourtIDBookBookIDBadRequest creates DeleteV1BomondCourtIDBookBookIDBadRequest with default headers values
func NewDeleteV1BomondCourtIDBookBookIDBadRequest() *DeleteV1BomondCourtIDBookBookIDBadRequest {

	return &DeleteV1BomondCourtIDBookBookIDBadRequest{}
}

// WithPayload adds the payload to the delete v1 bomond court Id book book Id bad request response
func (o *DeleteV1BomondCourtIDBookBookIDBadRequest) WithPayload(payload *models.ErrorResult) *DeleteV1BomondCourtIDBookBookIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete v1 bomond court Id book book Id bad request response
func (o *DeleteV1BomondCourtIDBookBookIDBadRequest) SetPayload(payload *models.ErrorResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteV1BomondCourtIDBookBookIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
