// Code generated by go-swagger; DO NOT EDIT.

package courts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"
)

// DeleteV1BomondCourtIDBookBookIDURL generates an URL for the delete v1 bomond court ID book book ID operation
type DeleteV1BomondCourtIDBookBookIDURL struct {
	BookID  string
	CourtID string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DeleteV1BomondCourtIDBookBookIDURL) WithBasePath(bp string) *DeleteV1BomondCourtIDBookBookIDURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DeleteV1BomondCourtIDBookBookIDURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *DeleteV1BomondCourtIDBookBookIDURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/v1/bomond/{court_id}/book/{book_id}"

	bookID := o.BookID
	if bookID != "" {
		_path = strings.Replace(_path, "{book_id}", bookID, -1)
	} else {
		return nil, errors.New("bookId is required on DeleteV1BomondCourtIDBookBookIDURL")
	}

	courtID := o.CourtID
	if courtID != "" {
		_path = strings.Replace(_path, "{court_id}", courtID, -1)
	} else {
		return nil, errors.New("courtId is required on DeleteV1BomondCourtIDBookBookIDURL")
	}

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *DeleteV1BomondCourtIDBookBookIDURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *DeleteV1BomondCourtIDBookBookIDURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *DeleteV1BomondCourtIDBookBookIDURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on DeleteV1BomondCourtIDBookBookIDURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on DeleteV1BomondCourtIDBookBookIDURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *DeleteV1BomondCourtIDBookBookIDURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
