// Code generated by go-swagger; DO NOT EDIT.

package courts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewDeleteV1BomondCourtIDBookBookIDParams creates a new DeleteV1BomondCourtIDBookBookIDParams object
//
// There are no default values defined in the spec.
func NewDeleteV1BomondCourtIDBookBookIDParams() DeleteV1BomondCourtIDBookBookIDParams {

	return DeleteV1BomondCourtIDBookBookIDParams{}
}

// DeleteV1BomondCourtIDBookBookIDParams contains all the bound params for the delete v1 bomond court ID book book ID operation
// typically these are obtained from a http.Request
//
// swagger:parameters DeleteV1BomondCourtIDBookBookID
type DeleteV1BomondCourtIDBookBookIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	BookID string
	/*
	  Required: true
	  In: path
	*/
	CourtID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteV1BomondCourtIDBookBookIDParams() beforehand.
func (o *DeleteV1BomondCourtIDBookBookIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rBookID, rhkBookID, _ := route.Params.GetOK("book_id")
	if err := o.bindBookID(rBookID, rhkBookID, route.Formats); err != nil {
		res = append(res, err)
	}

	rCourtID, rhkCourtID, _ := route.Params.GetOK("court_id")
	if err := o.bindCourtID(rCourtID, rhkCourtID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindBookID binds and validates parameter BookID from path.
func (o *DeleteV1BomondCourtIDBookBookIDParams) bindBookID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.BookID = raw

	return nil
}

// bindCourtID binds and validates parameter CourtID from path.
func (o *DeleteV1BomondCourtIDBookBookIDParams) bindCourtID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.CourtID = raw

	return nil
}
