// Code generated by go-swagger; DO NOT EDIT.

package courts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteV1BomondVnCourtIDBookBookIDHandlerFunc turns a function with the right signature into a delete v1 bomond vn court ID book book ID handler
type DeleteV1BomondVnCourtIDBookBookIDHandlerFunc func(DeleteV1BomondVnCourtIDBookBookIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteV1BomondVnCourtIDBookBookIDHandlerFunc) Handle(params DeleteV1BomondVnCourtIDBookBookIDParams) middleware.Responder {
	return fn(params)
}

// DeleteV1BomondVnCourtIDBookBookIDHandler interface for that can handle valid delete v1 bomond vn court ID book book ID params
type DeleteV1BomondVnCourtIDBookBookIDHandler interface {
	Handle(DeleteV1BomondVnCourtIDBookBookIDParams) middleware.Responder
}

// NewDeleteV1BomondVnCourtIDBookBookID creates a new http.Handler for the delete v1 bomond vn court ID book book ID operation
func NewDeleteV1BomondVnCourtIDBookBookID(ctx *middleware.Context, handler DeleteV1BomondVnCourtIDBookBookIDHandler) *DeleteV1BomondVnCourtIDBookBookID {
	return &DeleteV1BomondVnCourtIDBookBookID{Context: ctx, Handler: handler}
}

/*
	DeleteV1BomondVnCourtIDBookBookID swagger:route DELETE /v1/bomond.vn/{court_id}/book/{book_id} Courts deleteV1BomondVnCourtIdBookBookId

DeleteV1BomondVnCourtIDBookBookID delete v1 bomond vn court ID book book ID API
*/
type DeleteV1BomondVnCourtIDBookBookID struct {
	Context *middleware.Context
	Handler DeleteV1BomondVnCourtIDBookBookIDHandler
}

func (o *DeleteV1BomondVnCourtIDBookBookID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteV1BomondVnCourtIDBookBookIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
