// Code generated by go-swagger; DO NOT EDIT.

package courts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"bomond-tenis/internal/api/models"
)

// GetV1BomondCourtsOKCode is the HTTP code returned for type GetV1BomondCourtsOK
const GetV1BomondCourtsOKCode int = 200

/*
GetV1BomondCourtsOK Courts list retrieved

swagger:response getV1BomondCourtsOK
*/
type GetV1BomondCourtsOK struct {

	/*
	  In: Body
	*/
	Payload *models.SuccessResponse `json:"body,omitempty"`
}

// NewGetV1BomondCourtsOK creates GetV1BomondCourtsOK with default headers values
func NewGetV1BomondCourtsOK() *GetV1BomondCourtsOK {

	return &GetV1BomondCourtsOK{}
}

// WithPayload adds the payload to the get v1 bomond courts o k response
func (o *GetV1BomondCourtsOK) WithPayload(payload *models.SuccessResponse) *GetV1BomondCourtsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 bomond courts o k response
func (o *GetV1BomondCourtsOK) SetPayload(payload *models.SuccessResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1BomondCourtsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetV1BomondCourtsBadRequestCode is the HTTP code returned for type GetV1BomondCourtsBadRequest
const GetV1BomondCourtsBadRequestCode int = 400

/*
GetV1BomondCourtsBadRequest Bad request

swagger:response getV1BomondCourtsBadRequest
*/
type GetV1BomondCourtsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResult `json:"body,omitempty"`
}

// NewGetV1BomondCourtsBadRequest creates GetV1BomondCourtsBadRequest with default headers values
func NewGetV1BomondCourtsBadRequest() *GetV1BomondCourtsBadRequest {

	return &GetV1BomondCourtsBadRequest{}
}

// WithPayload adds the payload to the get v1 bomond courts bad request response
func (o *GetV1BomondCourtsBadRequest) WithPayload(payload *models.ErrorResult) *GetV1BomondCourtsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 bomond courts bad request response
func (o *GetV1BomondCourtsBadRequest) SetPayload(payload *models.ErrorResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1BomondCourtsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
