// Code generated by go-swagger; DO NOT EDIT.

package courts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetV1BomondVnCourtsHandlerFunc turns a function with the right signature into a get v1 bomond vn courts handler
type GetV1BomondVnCourtsHandlerFunc func(GetV1BomondVnCourtsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetV1BomondVnCourtsHandlerFunc) Handle(params GetV1BomondVnCourtsParams) middleware.Responder {
	return fn(params)
}

// GetV1BomondVnCourtsHandler interface for that can handle valid get v1 bomond vn courts params
type GetV1BomondVnCourtsHandler interface {
	Handle(GetV1BomondVnCourtsParams) middleware.Responder
}

// NewGetV1BomondVnCourts creates a new http.Handler for the get v1 bomond vn courts operation
func NewGetV1BomondVnCourts(ctx *middleware.Context, handler GetV1BomondVnCourtsHandler) *GetV1BomondVnCourts {
	return &GetV1BomondVnCourts{Context: ctx, Handler: handler}
}

/*
	GetV1BomondVnCourts swagger:route GET /v1/bomond.vn/courts Courts getV1BomondVnCourts

GetV1BomondVnCourts get v1 bomond vn courts API
*/
type GetV1BomondVnCourts struct {
	Context *middleware.Context
	Handler GetV1BomondVnCourtsHandler
}

func (o *GetV1BomondVnCourts) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetV1BomondVnCourtsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
