// Code generated by go-swagger; DO NOT EDIT.

package courts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetV1BomondCourtsHandlerFunc turns a function with the right signature into a get v1 bomond courts handler
type GetV1BomondCourtsHandlerFunc func(GetV1BomondCourtsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetV1BomondCourtsHandlerFunc) Handle(params GetV1BomondCourtsParams) middleware.Responder {
	return fn(params)
}

// GetV1BomondCourtsHandler interface for that can handle valid get v1 bomond courts params
type GetV1BomondCourtsHandler interface {
	Handle(GetV1BomondCourtsParams) middleware.Responder
}

// NewGetV1BomondCourts creates a new http.Handler for the get v1 bomond courts operation
func NewGetV1BomondCourts(ctx *middleware.Context, handler GetV1BomondCourtsHandler) *GetV1BomondCourts {
	return &GetV1BomondCourts{Context: ctx, Handler: handler}
}

/*
	GetV1BomondCourts swagger:route GET /v1/bomond/courts Courts getV1BomondCourts

GetV1BomondCourts get v1 bomond courts API
*/
type GetV1BomondCourts struct {
	Context *middleware.Context
	Handler GetV1BomondCourtsHandler
}

func (o *GetV1BomondCourts) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetV1BomondCourtsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
