// Code generated by go-swagger; DO NOT EDIT.

package courts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetV1BomondVnCourtIDBookParams creates a new GetV1BomondVnCourtIDBookParams object
//
// There are no default values defined in the spec.
func NewGetV1BomondVnCourtIDBookParams() GetV1BomondVnCourtIDBookParams {

	return GetV1BomondVnCourtIDBookParams{}
}

// GetV1BomondVnCourtIDBookParams contains all the bound params for the get v1 bomond vn court ID book operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetV1BomondVnCourtIDBook
type GetV1BomondVnCourtIDBookParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*JWT token for authorization
	  Required: true
	  In: header
	*/
	Authorization string
	/*
	  Required: true
	  In: path
	*/
	CourtID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetV1BomondVnCourtIDBookParams() beforehand.
func (o *GetV1BomondVnCourtIDBookParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := o.bindAuthorization(r.Header[http.CanonicalHeaderKey("Authorization")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	rCourtID, rhkCourtID, _ := route.Params.GetOK("court_id")
	if err := o.bindCourtID(rCourtID, rhkCourtID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAuthorization binds and validates parameter Authorization from header.
func (o *GetV1BomondVnCourtIDBookParams) bindAuthorization(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("Authorization", "header", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("Authorization", "header", raw); err != nil {
		return err
	}
	o.Authorization = raw

	return nil
}

// bindCourtID binds and validates parameter CourtID from path.
func (o *GetV1BomondVnCourtIDBookParams) bindCourtID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.CourtID = raw

	return nil
}
