// Code generated by go-swagger; DO NOT EDIT.

package courts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewPostV1BomondVnCourtIDBookParams creates a new PostV1BomondVnCourtIDBookParams object
//
// There are no default values defined in the spec.
func NewPostV1BomondVnCourtIDBookParams() PostV1BomondVnCourtIDBookParams {

	return PostV1BomondVnCourtIDBookParams{}
}

// PostV1BomondVnCourtIDBookParams contains all the bound params for the post v1 bomond vn court ID book operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostV1BomondVnCourtIDBook
type PostV1BomondVnCourtIDBookParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: body
	*/
	BookingRequest PostV1BomondVnCourtIDBookBody
	/*
	  Required: true
	  In: path
	*/
	CourtID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostV1BomondVnCourtIDBookParams() beforehand.
func (o *PostV1BomondVnCourtIDBookParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body PostV1BomondVnCourtIDBookBody
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("bookingRequest", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.BookingRequest = body
			}
		}
	}

	rCourtID, rhkCourtID, _ := route.Params.GetOK("court_id")
	if err := o.bindCourtID(rCourtID, rhkCourtID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCourtID binds and validates parameter CourtID from path.
func (o *PostV1BomondVnCourtIDBookParams) bindCourtID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.CourtID = raw

	return nil
}
