// Code generated by go-swagger; DO NOT EDIT.

package courts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"bomond-tenis/internal/api/models"
)

// PostV1BomondVnCourtIDBookOKCode is the HTTP code returned for type PostV1BomondVnCourtIDBookOK
const PostV1BomondVnCourtIDBookOKCode int = 200

/*
PostV1BomondVnCourtIDBookOK Court successfully booked

swagger:response postV1BomondVnCourtIdBookOK
*/
type PostV1BomondVnCourtIDBookOK struct {

	/*
	  In: Body
	*/
	Payload *models.SuccessResponse `json:"body,omitempty"`
}

// NewPostV1BomondVnCourtIDBookOK creates PostV1BomondVnCourtIDBookOK with default headers values
func NewPostV1BomondVnCourtIDBookOK() *PostV1BomondVnCourtIDBookOK {

	return &PostV1BomondVnCourtIDBookOK{}
}

// WithPayload adds the payload to the post v1 bomond vn court Id book o k response
func (o *PostV1BomondVnCourtIDBookOK) WithPayload(payload *models.SuccessResponse) *PostV1BomondVnCourtIDBookOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post v1 bomond vn court Id book o k response
func (o *PostV1BomondVnCourtIDBookOK) SetPayload(payload *models.SuccessResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostV1BomondVnCourtIDBookOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostV1BomondVnCourtIDBookBadRequestCode is the HTTP code returned for type PostV1BomondVnCourtIDBookBadRequest
const PostV1BomondVnCourtIDBookBadRequestCode int = 400

/*
PostV1BomondVnCourtIDBookBadRequest Bad request

swagger:response postV1BomondVnCourtIdBookBadRequest
*/
type PostV1BomondVnCourtIDBookBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResult `json:"body,omitempty"`
}

// NewPostV1BomondVnCourtIDBookBadRequest creates PostV1BomondVnCourtIDBookBadRequest with default headers values
func NewPostV1BomondVnCourtIDBookBadRequest() *PostV1BomondVnCourtIDBookBadRequest {

	return &PostV1BomondVnCourtIDBookBadRequest{}
}

// WithPayload adds the payload to the post v1 bomond vn court Id book bad request response
func (o *PostV1BomondVnCourtIDBookBadRequest) WithPayload(payload *models.ErrorResult) *PostV1BomondVnCourtIDBookBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post v1 bomond vn court Id book bad request response
func (o *PostV1BomondVnCourtIDBookBadRequest) SetPayload(payload *models.ErrorResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostV1BomondVnCourtIDBookBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
