// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"bomond-tenis/internal/api/models"
)

// DeleteV1BomondVnUsersUserIDOKCode is the HTTP code returned for type DeleteV1BomondVnUsersUserIDOK
const DeleteV1BomondVnUsersUserIDOKCode int = 200

/*
DeleteV1BomondVnUsersUserIDOK User successfully deleted

swagger:response deleteV1BomondVnUsersUserIdOK
*/
type DeleteV1BomondVnUsersUserIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.SuccessResponse `json:"body,omitempty"`
}

// NewDeleteV1BomondVnUsersUserIDOK creates DeleteV1BomondVnUsersUserIDOK with default headers values
func NewDeleteV1BomondVnUsersUserIDOK() *DeleteV1BomondVnUsersUserIDOK {

	return &DeleteV1BomondVnUsersUserIDOK{}
}

// WithPayload adds the payload to the delete v1 bomond vn users user Id o k response
func (o *DeleteV1BomondVnUsersUserIDOK) WithPayload(payload *models.SuccessResponse) *DeleteV1BomondVnUsersUserIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete v1 bomond vn users user Id o k response
func (o *DeleteV1BomondVnUsersUserIDOK) SetPayload(payload *models.SuccessResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteV1BomondVnUsersUserIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteV1BomondVnUsersUserIDBadRequestCode is the HTTP code returned for type DeleteV1BomondVnUsersUserIDBadRequest
const DeleteV1BomondVnUsersUserIDBadRequestCode int = 400

/*
DeleteV1BomondVnUsersUserIDBadRequest Bad request

swagger:response deleteV1BomondVnUsersUserIdBadRequest
*/
type DeleteV1BomondVnUsersUserIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResult `json:"body,omitempty"`
}

// NewDeleteV1BomondVnUsersUserIDBadRequest creates DeleteV1BomondVnUsersUserIDBadRequest with default headers values
func NewDeleteV1BomondVnUsersUserIDBadRequest() *DeleteV1BomondVnUsersUserIDBadRequest {

	return &DeleteV1BomondVnUsersUserIDBadRequest{}
}

// WithPayload adds the payload to the delete v1 bomond vn users user Id bad request response
func (o *DeleteV1BomondVnUsersUserIDBadRequest) WithPayload(payload *models.ErrorResult) *DeleteV1BomondVnUsersUserIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete v1 bomond vn users user Id bad request response
func (o *DeleteV1BomondVnUsersUserIDBadRequest) SetPayload(payload *models.ErrorResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteV1BomondVnUsersUserIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
