// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"bomond-tenis/internal/api/models"
)

// GetV1BomondVnUsersUserIDOKCode is the HTTP code returned for type GetV1BomondVnUsersUserIDOK
const GetV1BomondVnUsersUserIDOKCode int = 200

/*
GetV1BomondVnUsersUserIDOK User details retrieved

swagger:response getV1BomondVnUsersUserIdOK
*/
type GetV1BomondVnUsersUserIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.SuccessResponse `json:"body,omitempty"`
}

// NewGetV1BomondVnUsersUserIDOK creates GetV1BomondVnUsersUserIDOK with default headers values
func NewGetV1BomondVnUsersUserIDOK() *GetV1BomondVnUsersUserIDOK {

	return &GetV1BomondVnUsersUserIDOK{}
}

// WithPayload adds the payload to the get v1 bomond vn users user Id o k response
func (o *GetV1BomondVnUsersUserIDOK) WithPayload(payload *models.SuccessResponse) *GetV1BomondVnUsersUserIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 bomond vn users user Id o k response
func (o *GetV1BomondVnUsersUserIDOK) SetPayload(payload *models.SuccessResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1BomondVnUsersUserIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetV1BomondVnUsersUserIDBadRequestCode is the HTTP code returned for type GetV1BomondVnUsersUserIDBadRequest
const GetV1BomondVnUsersUserIDBadRequestCode int = 400

/*
GetV1BomondVnUsersUserIDBadRequest Bad request

swagger:response getV1BomondVnUsersUserIdBadRequest
*/
type GetV1BomondVnUsersUserIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResult `json:"body,omitempty"`
}

// NewGetV1BomondVnUsersUserIDBadRequest creates GetV1BomondVnUsersUserIDBadRequest with default headers values
func NewGetV1BomondVnUsersUserIDBadRequest() *GetV1BomondVnUsersUserIDBadRequest {

	return &GetV1BomondVnUsersUserIDBadRequest{}
}

// WithPayload adds the payload to the get v1 bomond vn users user Id bad request response
func (o *GetV1BomondVnUsersUserIDBadRequest) WithPayload(payload *models.ErrorResult) *GetV1BomondVnUsersUserIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 bomond vn users user Id bad request response
func (o *GetV1BomondVnUsersUserIDBadRequest) SetPayload(payload *models.ErrorResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1BomondVnUsersUserIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
