// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"bomond-tenis/internal/api/models"
)

// PutV1BomondVnUsersUserIDOKCode is the HTTP code returned for type PutV1BomondVnUsersUserIDOK
const PutV1BomondVnUsersUserIDOKCode int = 200

/*
PutV1BomondVnUsersUserIDOK User successfully updated

swagger:response putV1BomondVnUsersUserIdOK
*/
type PutV1BomondVnUsersUserIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.SuccessResponse `json:"body,omitempty"`
}

// NewPutV1BomondVnUsersUserIDOK creates PutV1BomondVnUsersUserIDOK with default headers values
func NewPutV1BomondVnUsersUserIDOK() *PutV1BomondVnUsersUserIDOK {

	return &PutV1BomondVnUsersUserIDOK{}
}

// WithPayload adds the payload to the put v1 bomond vn users user Id o k response
func (o *PutV1BomondVnUsersUserIDOK) WithPayload(payload *models.SuccessResponse) *PutV1BomondVnUsersUserIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put v1 bomond vn users user Id o k response
func (o *PutV1BomondVnUsersUserIDOK) SetPayload(payload *models.SuccessResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutV1BomondVnUsersUserIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutV1BomondVnUsersUserIDBadRequestCode is the HTTP code returned for type PutV1BomondVnUsersUserIDBadRequest
const PutV1BomondVnUsersUserIDBadRequestCode int = 400

/*
PutV1BomondVnUsersUserIDBadRequest Bad request

swagger:response putV1BomondVnUsersUserIdBadRequest
*/
type PutV1BomondVnUsersUserIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResult `json:"body,omitempty"`
}

// NewPutV1BomondVnUsersUserIDBadRequest creates PutV1BomondVnUsersUserIDBadRequest with default headers values
func NewPutV1BomondVnUsersUserIDBadRequest() *PutV1BomondVnUsersUserIDBadRequest {

	return &PutV1BomondVnUsersUserIDBadRequest{}
}

// WithPayload adds the payload to the put v1 bomond vn users user Id bad request response
func (o *PutV1BomondVnUsersUserIDBadRequest) WithPayload(payload *models.ErrorResult) *PutV1BomondVnUsersUserIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put v1 bomond vn users user Id bad request response
func (o *PutV1BomondVnUsersUserIDBadRequest) SetPayload(payload *models.ErrorResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutV1BomondVnUsersUserIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
