// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PutV1BomondVnUsersUserIDHandlerFunc turns a function with the right signature into a put v1 bomond vn users user ID handler
type PutV1BomondVnUsersUserIDHandlerFunc func(PutV1BomondVnUsersUserIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutV1BomondVnUsersUserIDHandlerFunc) Handle(params PutV1BomondVnUsersUserIDParams) middleware.Responder {
	return fn(params)
}

// PutV1BomondVnUsersUserIDHandler interface for that can handle valid put v1 bomond vn users user ID params
type PutV1BomondVnUsersUserIDHandler interface {
	Handle(PutV1BomondVnUsersUserIDParams) middleware.Responder
}

// NewPutV1BomondVnUsersUserID creates a new http.Handler for the put v1 bomond vn users user ID operation
func NewPutV1BomondVnUsersUserID(ctx *middleware.Context, handler PutV1BomondVnUsersUserIDHandler) *PutV1BomondVnUsersUserID {
	return &PutV1BomondVnUsersUserID{Context: ctx, Handler: handler}
}

/*
	PutV1BomondVnUsersUserID swagger:route PUT /v1/bomond.vn/users/{user_id} Users putV1BomondVnUsersUserId

PutV1BomondVnUsersUserID put v1 bomond vn users user ID API
*/
type PutV1BomondVnUsersUserID struct {
	Context *middleware.Context
	Handler PutV1BomondVnUsersUserIDHandler
}

func (o *PutV1BomondVnUsersUserID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutV1BomondVnUsersUserIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PutV1BomondVnUsersUserIDBody put v1 bomond vn users user ID body
//
// swagger:model PutV1BomondVnUsersUserIDBody
type PutV1BomondVnUsersUserIDBody struct {

	// email
	Email string `json:"email,omitempty"`

	// password
	Password string `json:"password,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this put v1 bomond vn users user ID body
func (o *PutV1BomondVnUsersUserIDBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this put v1 bomond vn users user ID body based on context it is used
func (o *PutV1BomondVnUsersUserIDBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PutV1BomondVnUsersUserIDBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutV1BomondVnUsersUserIDBody) UnmarshalBinary(b []byte) error {
	var res PutV1BomondVnUsersUserIDBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
